version: 2

jobs:
  build:
    working_directory: ~/repo/gs2-java-sdk
    docker:
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          CIRCLE_ARTIFACTS: /tmp/test-results
    steps:
      - checkout
      -
        run:
          name: OSの初期設定
          command: |
            sudo apt -q update
            sudo apt -q install -y --no-install-recommends gnupg2
            sudo curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python get-pip.py
            sudo pip install awscli requests GitPython
      -
        deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then

              aws s3 cp s3://gs2-repos/python/publish/${PUBLISH_VERSION}/publish-${PUBLISH_VERSION}.tar.gz ~/ && tar -zxvf ~/publish-${PUBLISH_VERSION}.tar.gz -C ~/

              mkdir -p ~/.m2/

              gpg --batch --import ~/publish-${PUBLISH_VERSION}/java/gs2-maven-gpg.asc
              cp ~/publish-${PUBLISH_VERSION}/java/settings.xml ~/.m2/

              echo 'use-agent' >> ~/.gnupg/gpg.conf
              echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf

              echo 'allow-loopback-pinentry' >> ~/.gnupg/gpg-agent.conf

              set +e

              for service in core auth key script lock job-queue account deploy distributor experience gateway inbox identifier inventory limit lottery matchmaking mission money project quest schedule realtime showcase stamina ; do
                cd ~/repo/gs2-java-sdk/gs2-java-sdk-$service/
                mvn install
                mvn deploy -DperformRelease=true -Dgpg.skip=false
              done

              set -e

              cd ~/repo/gs2-java-sdk
              mvn deploy -DperformRelease=true -Dgpg.skip=false
            fi
      -
        store_test_results:
          path: $CIRCLE_ARTIFACTS