version: 2

jobs:
  build:
    working_directory: ~/repo/gs2-java-sdk
    docker:
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          CIRCLE_ARTIFACTS: /tmp/test-results
    steps:
      - checkout
      -
        restore_cache:
          name: 依存関係をキャッシュから取得
          keys:
            - PUBLISH
      -
        run:
          name: OSの初期設定
          command: |
            sudo apt -q update
            sudo apt -q install -y --no-install-recommends gnupg2
            sudo curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python get-pip.py
            sudo pip install awscli requests GitPython
      -
        run:
          name: Publishスクリプトを取得
          command: |
            aws s3 cp s3://gs2-repos/python/publish/${PUBLISH_VERSION}/publish-${PUBLISH_VERSION}.tar.gz ~/ && tar -zxvf ~/publish-${PUBLISH_VERSION}.tar.gz -C ~/
      -
        save_cache:
          name: Publishスクリプトをキャッシュに保存
          key: PUBLISH
          paths:
            - ~/publish-${PUBLISH_VERSION}

      -
        run:
          name: テストをチェックアウト
          command: |
            cd ..
            git clone -b ${CIRCLE_BRANCH} git@github.com:gs2io/gs2-java-sdk-private.git || git clone -b develop git@github.com:gs2io/gs2-java-sdk-private.git
      -
        run:
          name: ターゲットを決定
          command: |
            cd ../gs2-java-sdk-private
            .circleci/targets.sh .circleci/filter_gs2-java-sdk.sh > targets
      -
        run:
          name: SDK をビルド
          command: |
            cd ../gs2-java-sdk
            mvn install -Dgpg.skip=true -Dmaven.test.skip=true
      -
        run:
          name: テストを実行
          command: |
            cd ../gs2-java-sdk-private
            .circleci/test.sh < targets

      -
        deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ~/publish-${PUBLISH_VERSION}/java/publish_maven.sh ~/publish-${PUBLISH_VERSION}/java/
            fi
      -
        run:
          name: javadocファイルをコピー
          command: |
            cp ./target/*-javadoc.jar $CIRCLE_ARTIFACTS
      -
        store_test_results:
          path: $CIRCLE_ARTIFACTS